export const SWITCH_TO_NEW = 'SWITCH_TO_NEW'
export const SWITCH_TO_PAST = 'SWITCH_TO_PAST'
export const ADD_SEARCH_QUERY = 'ADD_SEARCH_QUERY'
export const CLEAR_SEARCH_QUERY = 'CLEAR_SEARCH_QUERY'
