export const LOAD_PAST_ARTICLES = 'LOAD_PAST_ARTICLES'
export const LOAD_PAST_ARTICLES_SUCCESS = 'LOAD_PAST_ARTICLES_SUCCESS'

export type LoadPastArticlesConstants = typeof LOAD_PAST_ARTICLES | typeof LOAD_PAST_ARTICLES_SUCCESS
